---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Vpc
metadata:
  annotations:
    ufo.mirantis.com/netris-adminTenant: "Admin"
  name: cats
  namespace: cats
spec: {}
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeeringPolicy
metadata:
  name: allow-from-kcm-system
  namespace: cats
spec:
  local_vpc:
    name: cats
  allowed_vpcs:
    - vpcName: '*'
      vpcNamespace: kcm-system
