apiVersion: ufo.mirantis.com/v1alpha1
kind: NetworkBundle
metadata:
  name: cats
  namespace: kcm-system
spec:
  vpc: cats
  clusterName: cats-cluster
  allocations:
    subnetAllocations:
      - name: cats-mgmt-subnet
        prefixLength: 24
        subnetpool: default
        subnet: cats-mgmt-subnet
        network: cats-mgmt-net
        gateway: true
      - name: cats-data-subnet
        prefixLength: 24
        subnetpool: default
        subnet: cats-data-subnet
        network: cats-data-net
    networks:
      - name: cats-mgmt-net
        type: evpn
        evpn:
          type: l2
        vlan:
          id: "auto"
        dnsServers:
        - "4.2.2.1"
      - name: cats-data-net
        type: evpn
        evpn:
          type: l2
        vlan:
          id: "auto"
        dnsServers:
        - "4.2.2.1"
  networkv2:
    ethernets:
      eth1:
        match:
          macAddress:
            fromAnnotation:
              object: baremetalhost
              annotation: net_interface_mgmt_0_mac
        mtu: 1500
      eth2:
        match:
          macAddress:
            fromAnnotation:
              object: baremetalhost
              annotation: net_interface_mgmt_1_mac
        mtu: 1500
      eth3:
        match:
          macAddress:
            fromAnnotation:
              object: baremetalhost
              annotation: net_interface_data_0_mac
        mtu: 1500
      eth4:
        match:
          macAddress:
            fromAnnotation:
              object: baremetalhost
              annotation: net_interface_data_1_mac
        mtu: 1500
    bonds:
      bond0:
       parameters:
         mode: active-backup
       interfaces:
        - eth1
        - eth2
       addresses:
        - ipFromSubnet:
            name: cats-mgmt-subnet
       gatewayv4:
         gatewayFromSubnet:
           name: cats-mgmt-subnet
       mtu: 1500
       nameservers:
         addresses:
           dnsFromNetwork:
             name: cats-mgmt-net
      bond1:
       parameters:
         mode: active-backup
       interfaces:
        - eth3
        - eth4
       mtu: 1500
    vlans:
      data:
        id:
          vlanIdFromNetwork:
            name: cats-data-net
        link: bond1
        addresses:
         - ipFromSubnet:
             name: cats-data-subnet
        mtu: 1500
