---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeeringPolicy
metadata:
  name: allow-from-cats
  namespace: kcm-system
spec:
  local_vpc:
    name: internet
  allowed_vpcs:
    - vpcName: '*'
      vpcNamespace: cats
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeering
metadata:
  name: internet-to-cats
  namespace: kcm-system
spec:
  local:
    name: internet
  remote:
    name: cats
    namespace: cats
