image:
  repository: registry.ci.mirantis.com/k0rdent-bm/images/unified-fabric-operator
  tag: {{ ufo_image_tag }}
ufoConfig:
{% filter indent(2, first=True) %}{% include 'k8s/ufo/ufo_conf.yaml' %}{% endfilter %}
