# Variables here can be changed only at host level
# so they are permanent among all tasks
cumulus_new_password: "<CUMULUS_NEW_PASSWORD>1!"
netris_admin_password: "<NETRIS_ADMIN_PASSWORD>1!"
redfish_password: "<REDFISH_PASSWORD>"
ctl_public_ip: "<CTL_PUBLIC_IP>"
netris_license: "<NETRIS_LICENSE>"
sdn_provider: netris


netris_operator_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/netris-operator
netris_operator_image: registry.ci.mirantis.com/k0rdent-bm/images/netris-operator
netris_operator_chart_version: 0.0.1-f125b11
netris_operator_image_tag: 0.0.1-f125b11.1775730529

ufo_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/unified-fabric-operator
ufo_chart_version: 0.0.12-a803321
ufo_image_tag: 0.0.12-a803321.1779463775

verity_operator_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/verity-operator
verity_operator_chart_version: 0.0.5-58b641c
verity_operator_image_tag: 0.0.5-58b641c.1779263746
