---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetPoolAllocation
metadata:
  name: dogs-default
  namespace: kcm-system
spec:
  ip_version: 4
  prefix_length: 23
  source:
    subnetpool:
      name: default
  target:
    subnetpool:
      name: default
      namespace: dogs
      tags:
        - default
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetPoolAllocation
metadata:
  name: dogs-public
  namespace: kcm-system
spec:
  ip_version: 4
  prefix_length: 23
  source:
    subnetpool:
      name: public
  target:
    subnetpool:
      name: public
      namespace: dogs
      tags:
        - public
