apiVersion: ufo.mirantis.com/v1alpha1
kind: Vpc
metadata:
  annotations:
    ufo.mirantis.com/netris-adminTenant: "Admin"
  name: default
  namespace: kcm-system
spec: {}
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: pxe
  namespace: kcm-system
  annotations:
    ufo.mirantis.com/pxe: default
spec:
  vpc: default
  type: l2vpn
  vlan:
    id: "300"
  tags:
    - ufo.mirantis.com/pxe=default
  gateways: []
  dhcp:
    enabled: false
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Subnet
metadata:
  name: pxe
  namespace: kcm-system
spec:
  vpc: default
  cidr: 172.16.81.0/24
  tags: []
  network: pxe
